# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-24 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name to give to this public key', max_length=100)),
                ('key', models.TextField(help_text='Public key', max_length=100000)),
                ('fingerprint', models.CharField(blank=True, max_length=48, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text=b'User that created the instance.', on_delete=django.db.models.deletion.CASCADE, related_name='created_publickeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': [('view_public_key', 'Can view public key')],
            },
        ),
    ]
