# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-24 12:14
from __future__ import unicode_literals

from django.db import migrations

from atmo.models import PermissionMigrator


def assign_public_key_view_permission(apps, schema_editor):
    PublicKey = apps.get_model('public_keys', 'PublicKey')
    PermissionMigrator(apps, PublicKey, 'created_by').assign()


def remove_public_key_view_permission(apps, schema_editor):
    PublicKey = apps.get_model('jobs', 'PublicKey')
    PermissionMigrator(apps, PublicKey, 'created_by').remove()


class Migration(migrations.Migration):

    dependencies = [
        ('public_keys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            assign_public_key_view_permission,
            remove_public_key_view_permission,
        ),
    ]
