sudo: required
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - DJANGO_DEBUG=False
    - DJANGO_SECRET_KEY=bd2b6169a99f2561168eb6b39c3fe9ad4b184a2e485781a3c875a1d1052d469d
before_script:
  - cp .env-dist .env
install:
    pip install -U docker-compose
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
