version: '2'

services:
  db:
    image: postgres:9.4
  redis:
    image: redis:3.2

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DEVELOPMENT=1
      - DJANGO_SECRET_KEY=bd2b6169a99f2561168eb6b39c3fe9ad4b184a2e485781a3c875a1d1052d469d
    env_file:
      - .env
    volumes:
      - $PWD:/app
      - $PWD/coverage:/opt/coverage
    command: "true"

  web:
    extends:
      service: app
    ports:
      - "8000:8000"
    depends_on:
      - app
    links:
      - db
      - redis
    command: web-dev

  worker:
    extends:
      service: app
    links:
      - db
      - redis
    command: worker

  scheduler:
    extends:
      service: app
    links:
      - db
      - redis
    command: scheduler
