version: '2'

services:
  db:
    image: postgres:9.4
  redis:
    image: redis:3.2

  app:
    build: .
    environment:
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
    env_file:
      - .env

  web:
    extends:
      service: app
    ports:
      - "8000:8000"
    depends_on:
      - app
    links:
      - db
      - redis
    command: bin/run web

  worker:
    extends:
      service: app
    links:
      - db
      - redis
    volumes_from:
      - web
    command: bin/run worker

  scheduler:
    extends:
      service: app
    links:
      - db
      - redis
    volumes_from:
      - web
    command: bin/run scheduler
